version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: graphql-tools
    versions:
    - 7.0.2
    - 7.0.3
  - dependency-name: typeorm
    versions:
    - 0.2.30
    - 0.2.31
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
